k8s_yaml([
    'crds/cockroach-client.crd.yaml',
    'crds/cockroach-db.crd.yaml',
    'crds/cockroach-migration.crd.yaml',
    'crds/redis-db.crd.yaml'
])

k8s_yaml(helm(
    '../../deploy/operator',
    name='db',
    namespace='book-planner'
))