apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      containers:
      - name: app
        image: "{{ .Values.image }}"
        {{- if or .Values.secureEnv .Values.redis }}
        envFrom:
        {{- if .Values.redis }}
        - secretRef:
            name: "{{ .Values.redis.secret }}"
        {{- end }}
        {{- if .Values.secureEnv }}
        - secretRef:
            name: "{{ .Values.name }}-secure-env"
        {{- end }}
        {{- end }}
        env:
        - name: PROXY_PREFIX
          value: "{{ .Values.path }}"
        {{- if .Values.baseUrl }}
        - name: BASE_URL
          value: "{{ .Values.baseUrl }}"
        {{- end }}
        {{- range $key, $value := .Values.env }}
        - name: "{{ $key }}"
          value: "{{ tpl $value $ }}"
        {{- end }}