{{- if .Values.isValidationServer }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth-validator
spec:
  forwardAuth:
    address: http://{{ .Values.name }}.{{ .Release.Namespace }}.svc.cluster.local
    authResponseHeaders:
    - X-Auth-User
{{- else if .Values.isDefaultPage }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: default-redirect
spec:
  redirectRegex:
    regex: ".*"
    replacement: "http://{{ .Values.hostname }}{{ .Values.path }}"
{{- end }}