name: pages-login
labels: [ auth-frontend ]
# hostname:
# image:

path: "/login"
secure: false
env:
  REGISTER_URL: "http://{{ .Values.hostname }}/register"
  SUBMIT_URL: "http://{{ .Values.hostname}}/login"
  REDIRECT_URL: "http://{{ .Values.hostname}}/home"
  USERS_API_URL: "http://apis-users.{{ .Release.Namespace }}.svc.cluster.local"
  TOKENS_API_URL: "http://apis-tokens.{{ .Release.Namespace }}.svc.cluster.local"