name: pages-register
labels: [ auth-frontend ]

# hostname:
# image:

path: "/register"
secure: false

env:
  SUBMIT_URL: "{{ .hostname }}/register"
  LOGIN_URL: "{{ .hostname }}/login"
  REDIRECT_URL: "{{ .hostname }}/login?registered=true"
  USERS_API_URL: "http://apis-users.{{ .Release.Namespace }}.svc.cluster.local"