name: apis-auth
labels: [ auth-backend ]
# hostname:
# image:

env:
  LOGIN_URL: "http://{{ .Values.hostname }}/login"
  TOKENS_API_URL: "http://apis-tokens.{{ .Release.Namespace }}.svc.cluster.local"

isValidationServer: true